services:
    app:
        build:
            context: .
            network: host
        ports:
            - "8070:8070"
        volumes:
            - ./config.json:/app/config.json:ro
        restart: unless-stopped

